[package]
name = "chunking1"
version = "0.1.0"
edition = "2024"

[dependencies]
async-openai = "0.29.1"
dotenv = "0.15.0"
futures = "0.3.31"
tiktoken-rs = "0.7.0"
tokio = { version = "1.47.1", features = ["full"]}
